FROM alpine:latest

ENV	OCSERV_VERSION="1.1.3"

RUN	set -x && \
	apk add --no-cache \
	build-base \
	curl \
	gnupg \
	linux-headers \
	nettle \
	nettle-dev \
	gnutls \
	gnutls-dev \
	libev \
	libev-dev \
	readline \
	readline-dev \
	lz4-libs \
	lz4-dev \
	libseccomp \
	libseccomp-dev && \
	mkdir -p /build && \
	cd /build && \
	set -- \
		1F42418905D8206AA754CCDC29EE58B996865171 && \
	gpg --batch --keyserver hkps://keyserver.ubuntu.com --recv-keys $@ || \
	gpg --batch --keyserver hkps://peegeepee.com --recv-keys $@ && \
	gpg --yes --list-keys --fingerprint --with-colons | sed -E -n -e 's/^fpr:::::::::([0-9A-F]+):$/\1:6:/p' | gpg --import-ownertrust --yes
#
#
#	Download ocserv
#
RUN set -x && \
	curl --location --silent --output /build/ocserv-${OCSERV_VERSION}.tar.xz "https://www.infradead.org/ocserv/download/ocserv-${OCSERV_VERSION}.tar.xz" && \
	curl --location --silent --compressed --output /build/ocserv-${OCSERV_VERSION}.tar.xz.sig "https://www.infradead.org/ocserv/download/ocserv-${OCSERV_VERSION}.tar.xz.sig" && \
	gpg --verify /build/ocserv-${OCSERV_VERSION}.tar.xz.sig && \
	tar -xf /build/ocserv-${OCSERV_VERSION}.tar.xz -C /build && \
	rm -f /build/ocserv-${OCSERV_VERSION}.tar.xz /build/ocserv-${OCSERV_VERSION}.tar.xz.sig
#
#	Compile ocserv
#
RUN set -x && \
	cd /build/ocserv-${OCSERV_VERSION} && \
	./configure && \
	make -j`nproc` && \
	make install
